article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from article import views

app_name = "article"


urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
    path('contact/',include("contact.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "contact"

urlpatterns = [
    path('',views.contact,name = "contact"),

]

article/models.py
from tabnanny import verbose
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):

    CONTENT_CHOICES =[
        ("Tarih","Tarih"),
        ("Bilim","Bilim"),
    ]
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE,verbose_name="Yazar")
    title = models.CharField(max_length=50,verbose_name="Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    content_type = models.CharField(max_length = 30, choices=CONTENT_CHOICES, default="Tarih",verbose_name = "İçerik Türü")
    article_image = models.FileField(blank = True,null = True,verbose_name= "Makaleye Fotoğraf Ekle(Opsiyonel)" )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete= models.CASCADE, verbose_name="Makale",related_name="comments")
    comment_author = models.CharField(max_length=50,verbose_name= "İsim")
    comment_content = models.CharField(max_length= 200,verbose_name= "Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

contact/models.py
from django.db import models
from django.core.validators import RegexValidator

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length = 200)
    email = models.EmailField()
    subject = models.TextField()

    def __str__(self):
        return self.name

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields =["title","content","content_type","article_image"]

article/views.py
from curses.ascii import HT
from webbrowser import get
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages

# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    

    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles})

def index(request):
    #return HttpResponse("Anasayfa")
    context = {
            "numbers": [1,2,3,4,5,6]
    }
    return render(request,"index.html",context)

def about(request):
    return render(request,"about.html")

@login_required(login_url= "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)

@login_required(login_url= "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)

        article.author = request.user
        article.save()

        messages.success(request,"Makale Başarıyla Oluşturuldu")
        return redirect("article:dashboard")
    

    return render(request,"addarticle.html",{"form":form})

def detail(request,id):
    
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id=id)
    
    comments= article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})

@login_required(login_url= "user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance= article)
    if form.is_valid():

        if article.author.id == request.user.id:        
            article = form.save(commit=False)
            article.author = request.user        
            article.save()

            messages.success(request,"Makale Başarıyla Güncellendi")
            return redirect("article:dashboard")
        else:
            messages.info(request,"Bu Makale Size Ait Olmadığı İçin Değişiklik Yapamazsınız")
            return redirect("article:dashboard")

    return render(request,"update.html",{"form":form})

@login_required(login_url= "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)
    if article.author.id == request.user.id:        
        article.delete()

        messages.success(request,"Makale Başarıyla Silindi")
        return redirect("article:dashboard")
    else:
        messages.info(request,"Bu Makale Size Ait Olmadığı İçin Değişiklik Yapamazsınız")
        return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
 
        newComment = Comment(comment_author = comment_author, comment_content = comment_content)
        newComment.article = article
        newComment.save()

    return redirect(reverse("article:detail",kwargs={"id":id}))

contact/views.py
from django.shortcuts import render,redirect
from .models import Contact
from django.http import HttpResponse
from django.contrib import messages
# Create your views here.

def contact(request):
    if request.method == "POST":
        contact = Contact()
        name = request.POST.get("name")
        email = request.POST.get("email")
        subject = request.POST.get("subject")
        contact.name = name
        contact.email = email
        contact.subject = subject
        contact.save()

        messages.success(request, "Düşüncelerinizi Dikkate Alacağız Şimdiden Teşekkür Ederiz...")
        return redirect("index")
    return render(request,"contact.html")

templates/about.html
{% extends "layout.html" %}

{% block body %}

<h3>Hakkımda</h3>
<hr>

<p>
Özellikle Yazılım, Bilim ve Tarih konularına merak duyan; öğrendiği ve öğreneceği her şeyi sizlerle paylaşacak olan Fen Lisesi öğrencisi...
</p>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
    <h3>Makale Oluştur</h3>
    <hr>
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <br>
        <button type = "submit" class = "btn btn-danger">Makale Oluştur</button>

    </form> 
    </div>
</div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<div class = "row">
        <div class ="col-md-10 offset-med-3" >
                <h3>Makaleler</h3>
                <hr>
        </div>
</div>
                <!-- Side widgets-->
                <div class="col-md-10 offset-med-3">
                    <!-- Search widget-->
                    <form>
                    {% csrf_token %}
                    <div class="card mb-4">
                        <div class="card-header">Ara</div>
                        <div class="card-body">
                            <div class="input-group">
                            
                            <input type="text" name = "keyword" class="form-control"  maxlength="64" placeholder="Ara...">
                            <button type="submit" class="btn btn-primary">Ara</button>
                            
                            </div>
                        </div>
                    </div>
                    </form>
                    <!-- Categories widget-->
                    
                </div>
{% if articles %}

{% for article in articles %}
<div class="row">
    <div class="col-md-10 offset-med-3">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <a href="{% url 'article:detail' article.id %}"><h2 class="fw-bolder mb-1">{{article.title}}</h2></a> 
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">{{article.author.username}} tarafından yayınlandı</div>
                <hr>
                <div class="text-muted fst-italic mb-2">{{article.created_date}}</div>
                <hr>
                <!-- Post categories-->
                <a class="badge badge-secondary" href="#!">
                {{article.content_type}}
                </a>
            </header>
            <!-- Preview image figure-->
            {% if article.article_image %}
            <a href="{% url 'article:detail' article.id %}"><figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure></a>    
            {% endif %}
                        
            <!-- Post content-->
            <section class="mb-5">
                <p>
                    {{article.content|safe|truncatewords:50}}
                </p>
                
                <a  href="{% url 'article:detail' article.id %}" class = "btn btn-danger">Devamını Oku</a>
                <!--style ="float: right;"-->
                <hr>
            </section>
        </article>

{% endfor %}


{% else %}


        <div class ="col-md-10 offset-med-3" >
            <div class="card mb-4">
                <div class = "alert alert-danger">
                    Makale Bulunamadı
                </div>
            </div>
        </div>

{% endif %}



{% endblock body %}

templates/contact.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<!------ Include the above in your HEAD tag ---------->

<div class="container contact-form">
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <h3>İletişim</h3>
               <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" name="name" class="form-control" placeholder="İsminiz *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="email" class="form-control" placeholder="Email Adresiniz *" value="" />
                        </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea name="subject" class="form-control" placeholder="Mesaj *" style="width: 100%; height: 150px;"></textarea>
                        </div>
                    </div>
                        <button type = "submit" class = "btn btn-danger">Gönder</button>
                    </div>
                    
                </div>
            </form>
</div>
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz, <small>{{request.user.username}}</small>
</p>
<hr>
<a class ="btn btn-danger" href = "{% url 'article:addarticle' %}">Makale Ekle</a>
<hr>
<div style = "margin-top : 100px;"class = "container">

{% if articles %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Başlık</th>
      <th scope="col">Yazar</th>
      <th scope="col">Yayınlanma Tarihi</th>
      <th scope="col">İçerik Türü</th>
      <th scope="col">Güncelle</th>
      <th scope="col">Sil</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
      <th scope="row">{{article.id}}</th>
      <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
      <td>{{article.author.username}}</td>
      <td>{{article.created_date}}</td>
      <td>{{article.content_type}}</td>
      <td><a href="{% url 'article:update' article.id %}" class = "btn btn-danger">Güncelle</a></td>
      <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Sil</a></td>
    </tr>
    {% endfor %}

    <!--- <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
      <td>@mdo</td>
    </tr> -->

    
  </tbody>
</table>
{% else %}

<div class = "alert alert-danger">Henüz bir makaleniz bulunmuyor...</div>

{% endif %}



{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h3 class="fw-bolder mb-1">{{article.title}}</h3>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">{{article.author.username}} tarafından yayınlandı</div>
                            <hr>
                            <div class="text-muted fst-italic mb-2">{{article.created_date}}</div>
                            <hr>
                            <!-- Post categories-->
                            <a class="badge badge-secondary" href="#!">
                            {{article.content_type}}
                            </a>
                        </header>
                        <!-- Preview image figure-->
                        {% if article.article_image %}
                        <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure>    
                        {% endif %}
                        
                        <!-- Post content-->
                        <section class="mb-5">
                            <p>
                                {{article.content|safe}}
                            </p>
                        </section>
                    </article>
                </div>
            </div>
                    <!-- Comments section-->
                    <section class="mb-5">
                        <div class="card bg-light">
                            
                            <div class="card-body">
                                <form method = "post" action = "{% url 'article:comment' article.id %}">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for = "formGroupExampleInput">İsim</label>
                                        <input name = "comment_author" type="text" class="form-control" id= "formGroupExampleInput" placeholder="İsim">
                                    </div>
                                    <div class="form-group">
                                        <label for="formGroupExampleInput">Yorum</label>
                                        <textarea name = "comment_content" rows = "3" class="form-control" placeholder="Yorum Bırakın"></textarea>
                                    </div>
                                    <button type="submit" class ="btn btn-primary">Ekle</button>
                                </form>
                                {% if comments %}
                                {% for comment in comments %}
                                <hr>
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                        <div class="ms-3">
                                            <h6 class="fw-bold">{{comment.comment_author}}</h6>
                                            <sup>{{comment.comment_date}}</sup><br>
                                            {{comment.comment_content}}
                                        </div>
                                </div>
                                
                                {% endfor %}
                                
                                {% else %}
                                <div class = "alert alert-danger ">
                                    Bu makaleye herhangi bir yorum yazılmamış, ilk yorum yapan siz olun!
                                </div>
                                {% endif %}                                                   
                            </div>
                        </div>
                    </section>

                    
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <!--<form action="/articles/" method = "post">
                    {% csrf_token %}
                    <div class="card mb-4">
                        <div class="card-header">Ara</div>
                        <div class="card-body">
                            <div class="input-group">
                            
                            <input type="text" name = "keyword" class="form-control"  maxlength="64" placeholder="Ara...">
                            <button type="submit" class="btn btn-primary">Ara</button>
                            
                            </div>
                        </div>
                    </div>
                    </form>-->
                    <!-- Categories widget-->
                </div>
            </div>


{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron text-center">
        <h3>Kişisel Bloğum "S19 Blog"a Hoşgeldiniz</h3>
        <p>Bu blog sayfasında size her konuda bilgi aktarmaya çalışacağım aktaracağım</p>
</div>
<p>
        {% if request.user.is_authenticated %}
                Giriş Yapılmış, {{request.user.username}}
        {% else %}
                Giriş Yapılmamış
        {% endif %}

</p>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>S19BLOG</title>
</head>
<body>

        {% include "includes/navbar.html" %}


        
        <div style = "margin-top : 100px; margin_bottom:50px;"class = "container">
            {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{message.tags}}">{{ message }}</div>
                    {% endif %}
                    
                    {% endfor %}
                
            {% endif %}
            {% block body %}
            
            {% endblock body %}
        
        </div>

        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        
        <script src = "{% static 'js/bootstrap.min.js' %}"></script>
        <script src = "{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
    <h3>Giriş Yap</h3>
    <hr>
    <form method = "post">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type = "submit" class = "btn btn-danger">Giriş Yap</button>

    </form> 
    </div>
</div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
    <h3>Kayıt Ol</h3>
    <hr>
    <form method = "post">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type = "submit" class = "btn btn-danger">Kayıt Ol</button>

    </form> 
    </div>
</div>

{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
    <h3>Makale Güncelle</h3>
    <hr>
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <br>
        <button type = "submit" class = "btn btn-danger">Güncelle</button>

    </form> 
    </div>
</div>

{% endblock body %}